//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApplication.Infrastructure.Mapping {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApplication.Infrastructure.Mapping.SqlResource", typeof(SqlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM [user] WHERE email = @email AND shown = 1.
        /// </summary>
        internal static string CheckEmail {
            get {
                return ResourceManager.GetString("CheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM [user] WHERE username = @username AND shown = 1.
        /// </summary>
        internal static string CheckUsername {
            get {
                return ResourceManager.GetString("CheckUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[recipe]
        ///   SET [shown] = 0
        /// WHERE recipeId = @recipeId.
        /// </summary>
        internal static string DeleteRecipe {
            get {
                return ResourceManager.GetString("DeleteRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [user] SET shown = 0 WHERE userID = @id.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username, d.* FROM recipe r join dessert d on r.recipeId = d.FK_recipeId INNER JOIN [user] u on r.FK_authorId = u.userID WHERE r.recipeId = @id.
        /// </summary>
        internal static string GetDessertById {
            get {
                return ResourceManager.GetString("GetDessertById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [maincourse-diet] WHERE FK_MainCourseId = @id.
        /// </summary>
        internal static string GetDietaryTypes {
            get {
                return ResourceManager.GetString("GetDietaryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*,u.username,d.* FROM recipe r JOIN [user] u on r.FK_authorid = u.userID JOIN drink d on r.recipeId = d.FK_recipeId WHERE r.recipeId=@id.
        /// </summary>
        internal static string GetDrinkById {
            get {
                return ResourceManager.GetString("GetDrinkById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT password FROM [user] WHERE username = @username.
        /// </summary>
        internal static string GetHashedPasswordByUsername {
            get {
                return ResourceManager.GetString("GetHashedPasswordByUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username, m.* FROM recipe r join maincourse m on r.recipeId = m.FK_recipeId INNER JOIN [user] u on r.FK_authorId = u.userID WHERE r.recipeId = @id.
        /// </summary>
        internal static string GetMainCourseById {
            get {
                return ResourceManager.GetString("GetMainCourseById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username FROM recipe r LEFT JOIN [user] u ON r.FK_authorId = u.userID WHERE r.recipeId = @id.
        /// </summary>
        internal static string GetRecipeById {
            get {
                return ResourceManager.GetString("GetRecipeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [user] WHERE email=@username.
        /// </summary>
        internal static string GetUserByEmail {
            get {
                return ResourceManager.GetString("GetUserByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [user] WHERE userID=@id.
        /// </summary>
        internal static string GetUserById {
            get {
                return ResourceManager.GetString("GetUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [user] WHERE username=@username.
        /// </summary>
        internal static string GetUserByName {
            get {
                return ResourceManager.GetString("GetUserByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[dessert]
        ///           ([FK_recipeId]
        ///           ,[desserttype]
        ///           ,[servingmethod]
        ///           ,[topping])
        ///     VALUES
        ///           (@recipeId
        ///           ,@dessertType
        ///           ,@servingMethod
        ///           ,@topping).
        /// </summary>
        internal static string InsertDessert {
            get {
                return ResourceManager.GetString("InsertDessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[mainCourse-Diet]
        ///           ([FK_MainCourseId]
        ///           ,[FK_DietaryRestictionId])
        ///     VALUES
        ///           (@mainCourseId
        ///           ,@DietId).
        /// </summary>
        internal static string InsertDietaryRestriction {
            get {
                return ResourceManager.GetString("InsertDietaryRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[drink]
        ///           ([FK_recipeId]
        ///           ,[alcoholic]
        ///           ,[drinktype]
        ///           ,[glasstype])
        ///     VALUES
        ///           (@recipeid
        ///           ,@alcoholic
        ///           ,@drinktype
        ///           ,@glasstype).
        /// </summary>
        internal static string InsertDrink {
            get {
                return ResourceManager.GetString("InsertDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[maincourse]
        ///           ([FK_recipeId]
        ///           ,[cuisineType]
        ///           ,[servingSuggestion])
        ///     VALUES
        ///           (@recipeid
        ///           ,@cuisinetype
        ///           ,@servingsuggestion);.
        /// </summary>
        internal static string InsertMainCourse {
            get {
                return ResourceManager.GetString("InsertMainCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[recipe]
        ///           (FK_authorId
        ///           ,name
        ///           ,description
        ///           ,FK_recipetype
        ///           ,Ingredients
        ///           ,preptime
        ///           ,cooktime
        ///           ,steps
        ///           ,shown
        ///           ,image)
        ///     VALUES
        ///           (@authorid
        ///           ,@name
        ///           ,@desc
        ///           ,@recipetype
        ///           ,@Ingredients
        ///           ,@preptime
        ///           ,@cooktime
        ///           ,@steps
        ///           , 1
        ///           ,@image); SELECT SCOPE_IDENTITY();.
        /// </summary>
        internal static string InsertRecipe {
            get {
                return ResourceManager.GetString("InsertRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[recipe]
        ///           (FK_authorId
        ///           ,name
        ///           ,description
        ///           ,FK_recipetype
        ///           ,Ingredients
        ///           ,preptime
        ///           ,cooktime
        ///           ,steps
        ///           ,shown)
        ///     VALUES
        ///           (@authorid
        ///           ,@name
        ///           ,@desc
        ///           ,@recipetype
        ///           ,@Ingredients
        ///           ,@preptime
        ///           ,@cooktime
        ///           ,@steps
        ///           , 1); SELECT SCOPE_IDENTITY();.
        /// </summary>
        internal static string InsertRecipeNoImage {
            get {
                return ResourceManager.GetString("InsertRecipeNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[user]
        ///           ([username]
        ///           ,[password]
        ///           ,[firstname]
        ///           ,[middlename]
        ///           ,[lastname]
        ///           ,[email]
        ///           ,[admin]
        ///           ,[shown])
        ///     VALUES
        ///           (@username
        ///           ,@password
        ///           ,@firstname
        ///           ,@middlename
        ///           ,@lastname
        ///           ,@email
        ///           ,@admin
        ///           ,1).
        /// </summary>
        internal static string InsertUser {
            get {
                return ResourceManager.GetString("InsertUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[dessert] SET
        ///           [desserttype] = @desserttype
        ///           ,[servingmethod] = @servingmethod
        ///           ,[topping] = @topping
        ///WHERE [FK_recipeId] = @recipeId.
        /// </summary>
        internal static string UpdateDessert {
            get {
                return ResourceManager.GetString("UpdateDessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[drink] SET
        ///           [alcoholic] = @alcoholic
        ///           ,[drinktype] = @drinktype
        ///           ,[glasstype] = @glasstype
        ///WHERE [FK_recipeId] = @recipeId.
        /// </summary>
        internal static string UpdateDrink {
            get {
                return ResourceManager.GetString("UpdateDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[maincourse] SET
        ///           [cuisineType] = @cuisineType
        ///           ,[servingSuggestion] = @servingsuggestion
        ///WHERE [FK_recipeId] = @recipeId.
        /// </summary>
        internal static string UpdateMainCourse {
            get {
                return ResourceManager.GetString("UpdateMainCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[recipe]
        ///   SET [FK_authorId] = @authorid
        ///      ,[name] = @name
        ///      ,[description] = @desc
        ///      ,[FK_recipetype] = @recipetype
        ///      ,[Ingredients] = @Ingredients
        ///      ,[preptime] = @preptime
        ///      ,[cooktime] = @cooktime
        ///      ,[steps] = @steps
        ///      ,[shown] = @shown
        ///      ,[image] = @image
        ///WHERE recipeId = @recipeId; 
        ///SELECT SCOPE_IDENTITY();.
        /// </summary>
        internal static string UpdateRecipe {
            get {
                return ResourceManager.GetString("UpdateRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[user] 
        ///          SET username=@username, password=@password, firstname=@firstname, middlename=@middlename, lastname=@lastname, email=@email, admin=@admin, shown=@shown WHERE userID=@id.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username, d.* FROM recipe r join dessert d on r.recipeId = d.FK_recipeId INNER JOIN [user] u on r.FK_authorId = u.userID WHERE r.shown = 1.
        /// </summary>
        internal static string ViewActiveDesserts {
            get {
                return ResourceManager.GetString("ViewActiveDesserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username, d.* FROM recipe r join drink d on r.recipeId = d.FK_recipeId INNER JOIN [user] u on r.FK_authorId = u.userID WHERE r.shown = 1.
        /// </summary>
        internal static string ViewActiveDrinks {
            get {
                return ResourceManager.GetString("ViewActiveDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username, m.* FROM recipe r join maincourse m on r.recipeId = m.FK_recipeId INNER JOIN [user] u on r.FK_authorId = u.userID WHERE r.shown = 1.
        /// </summary>
        internal static string ViewActiveMainCourse {
            get {
                return ResourceManager.GetString("ViewActiveMainCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username FROM recipe r LEFT JOIN [user] u ON r.FK_authorId = u.userID WHERE r.shown = 1.
        /// </summary>
        internal static string ViewActiveRecipes {
            get {
                return ResourceManager.GetString("ViewActiveRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username FROM recipe r LEFT JOIN [user] u ON r.FK_authorId = u.userID WHERE r.shown = 1 AND r.FK_recipetype = @type.
        /// </summary>
        internal static string ViewActiveRecipesPerType {
            get {
                return ResourceManager.GetString("ViewActiveRecipesPerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [user] WHERE shown = 1.
        /// </summary>
        internal static string ViewActiveUsers {
            get {
                return ResourceManager.GetString("ViewActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username FROM recipe r LEFT JOIN [user] u ON r.FK_authorId = u.userID WHERE r.FK_recipetype = 3.
        /// </summary>
        internal static string ViewAllDessert {
            get {
                return ResourceManager.GetString("ViewAllDessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username FROM recipe r LEFT JOIN [user] u ON r.FK_authorId = u.userID WHERE r.FK_recipetype = 2.
        /// </summary>
        internal static string ViewAllDrinks {
            get {
                return ResourceManager.GetString("ViewAllDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username, m.* FROM recipe r join maincourse m on r.recipeId = m.FK_recipeId INNER JOIN [user] u on r.FK_authorId = u.userID.
        /// </summary>
        internal static string ViewAllMainCourses {
            get {
                return ResourceManager.GetString("ViewAllMainCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username FROM recipe r LEFT JOIN [user] u ON r.FK_authorId = u.userID.
        /// </summary>
        internal static string ViewAllRecipes {
            get {
                return ResourceManager.GetString("ViewAllRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [user].
        /// </summary>
        internal static string ViewAllUsers {
            get {
                return ResourceManager.GetString("ViewAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r.*, u.username FROM recipe r LEFT JOIN [user] u ON r.FK_authorId = u.userID WHERE r.shown = 1 AND r.FK_authorId = @userId.
        /// </summary>
        internal static string ViewRecipesFromUser {
            get {
                return ResourceManager.GetString("ViewRecipesFromUser", resourceCulture);
            }
        }
    }
}
